# webui url
webui_url: http://127.0.0.1:7860

# 画像フォルダ
image_folder: .\image

# ファイル名の最後に付ける識別子
image_suffix: _upscale

setting_list:
  # /////////////////////////////////
  # プロンプトの変換をしない設定
  simple:
    # apiパラメーター
    api_params:
      steps: 30
      cfg_scale: 7
      denoising_strength: 0.55
      sampler_name: 'DPM++ 2M Karras'
      batch_size: 1

    # アップスケール比率
    upscale: 2

    # NAI weight を SD weight に変換するか
    convert_nai_weight: False

  # /////////////////////////////////
  # プロンプトの変換をする設定
  change_prompt:
    # apiパラメーター
    api_params:
      steps: 30
      cfg_scale: 7
      denoising_strength: 0.55
      sampler_name: 'DPM++ 2M Karras'
      batch_size: 1

    # アップスケール比率
    upscale: 1.5

    # NAI weight を SD weight に変換するか
    convert_nai_weight: True

    # 削除プロンプト
    remove_positive_prompt:
      - "{{{{best quality,amazing quality,very aesthetic,absurdres}}}}"
      - "best quality, amazing quality, very aesthetic, absurdres"

    # 置換プロンプト
    replace_positive_prompt:
      -
        before: "flat chest"
        after: "large breasts"

    # 追加プロンプト
    add_positive_prompt:
      - "(hair ribbons:1.3)"
      - "(beachball:1.3)"

    # 削除ネガティブプロンプト
    remove_negative_prompt:
      - "nsfw, lowres, {bad}, error, fewer, extra, missing, worst quality, jpeg artifacts, bad quality, watermark, unfinished, displeasing, chromatic aberration, signature, extra digits, artistic error, username, scan, [abstract], lowres,bad,text,error,missing,extra,fewer,cropped,jpg artifacts,worst quality,bad quality,watermark,displeasing,unfinished,chromatic aberration,scan,scan artifacts,floating cock,censored,bar censor,multiple views,navel,"

    # 置換ネガティブプロンプト
    # replace_negative_prompt:
    #   -
    #     before: aaaa
    #     after: bbbb

    # 追加ネガティブプロンプト
    add_negative_prompt:
      - "negative_hand-neg"
      - "(worst quality, low quality:1.4),(lip, nose, tooth, rouge, lipstick, eyeshadow:1.4),(jpeg artifacts:1.4),"




